Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pyximport
import numpy as np

solver_name = "simpleNetwork"

pyximport.install(
    setup_args={"include_dirs": np.get_include()},
    reload_support=True,
    inplace=True,
    language_level=3,
)

simple_solver_run = pyximport.load_module(
    f"{solver_name}_solver_run",
    f"{solver_name}_solver_run.pyx",
    build_inplace=True,
    pyxbuild_dir="_dengo_temp",
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
File [0;32m~/.local/lib/python3.8/site-packages/pyximport/pyximport.py:214[0m, in [0;36mload_module[0;34m(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)[0m
[1;32m    213[0m         module_name [38;5;241m=[39m name
[0;32m--> 214[0m     so_path [38;5;241m=[39m [43mbuild_module[49m[43m([49m[43mmodule_name[49m[43m,[49m[43m [49m[43mpyxfilename[49m[43m,[49m[43m [49m[43mpyxbuild_dir[49m[43m,[49m
[1;32m    215[0m [43m                           [49m[43minplace[49m[38;5;241;43m=[39;49m[43mbuild_inplace[49m[43m,[49m[43m [49m[43mlanguage_level[49m[38;5;241;43m=[39;49m[43mlanguage_level[49m[43m)[49m
[1;32m    216[0m mod [38;5;241m=[39m imp[38;5;241m.[39mload_dynamic(name, so_path)

File [0;32m~/.local/lib/python3.8/site-packages/pyximport/pyximport.py:176[0m, in [0;36mbuild_module[0;34m(name, pyxfilename, pyxbuild_dir, inplace, language_level)[0m
[1;32m    175[0m [38;5;28;01mdef[39;00m [38;5;21mbuild_module[39m(name, pyxfilename, pyxbuild_dir[38;5;241m=[39m[38;5;28;01mNone[39;00m, inplace[38;5;241m=[39m[38;5;28;01mFalse[39;00m, language_level[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m--> 176[0m     [38;5;28;01massert[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists(pyxfilename), [38;5;124m"[39m[38;5;124mPath does not exist: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m pyxfilename
[1;32m    177[0m     handle_dependencies(pyxfilename)

[0;31mAssertionError[0m: Path does not exist: simpleNetwork_solver_run.pyx

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 13>[0;34m()[0m
[1;32m      4[0m solver_name [38;5;241m=[39m [38;5;124m"[39m[38;5;124msimpleNetwork[39m[38;5;124m"[39m
[1;32m      6[0m pyximport[38;5;241m.[39minstall(
[1;32m      7[0m     setup_args[38;5;241m=[39m{[38;5;124m"[39m[38;5;124minclude_dirs[39m[38;5;124m"[39m: np[38;5;241m.[39mget_include()},
[1;32m      8[0m     reload_support[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m      9[0m     inplace[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m     10[0m     language_level[38;5;241m=[39m[38;5;241m3[39m,
[1;32m     11[0m )
[0;32m---> 13[0m simple_solver_run [38;5;241m=[39m [43mpyximport[49m[38;5;241;43m.[39;49m[43mload_module[49m[43m([49m
[1;32m     14[0m [43m    [49m[38;5;124;43mf[39;49m[38;5;124;43m"[39;49m[38;5;132;43;01m{[39;49;00m[43msolver_name[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m_solver_run[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m     15[0m [43m    [49m[38;5;124;43mf[39;49m[38;5;124;43m"[39;49m[38;5;132;43;01m{[39;49;00m[43msolver_name[49m[38;5;132;43;01m}[39;49;00m[38;5;124;43m_solver_run.pyx[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m     16[0m [43m    [49m[43mbuild_inplace[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m
[1;32m     17[0m [43m    [49m[43mpyxbuild_dir[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m_dengo_temp[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m     18[0m [43m)[49m

File [0;32m~/.local/lib/python3.8/site-packages/pyximport/pyximport.py:231[0m, in [0;36mload_module[0;34m(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)[0m
[1;32m    228[0m exc [38;5;241m=[39m [38;5;167;01mImportError[39;00m([38;5;124m"[39m[38;5;124mBuilding module [39m[38;5;132;01m%s[39;00m[38;5;124m failed: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m (
[1;32m    229[0m     name, traceback[38;5;241m.[39mformat_exception_only([38;5;241m*[39msys[38;5;241m.[39mexc_info()[:[38;5;241m2[39m])))
[1;32m    230[0m [38;5;28;01mif[39;00m sys[38;5;241m.[39mversion_info[[38;5;241m0[39m] [38;5;241m>[39m[38;5;241m=[39m [38;5;241m3[39m:
[0;32m--> 231[0m     [38;5;28;01mraise[39;00m exc[38;5;241m.[39mwith_traceback(tb)
[1;32m    232[0m [38;5;28;01melse[39;00m:
[1;32m    233[0m     exec([38;5;124m"[39m[38;5;124mraise exc, None, tb[39m[38;5;124m"[39m, {[38;5;124m'[39m[38;5;124mexc[39m[38;5;124m'[39m: exc, [38;5;124m'[39m[38;5;124mtb[39m[38;5;124m'[39m: tb})

File [0;32m~/.local/lib/python3.8/site-packages/pyximport/pyximport.py:214[0m, in [0;36mload_module[0;34m(name, pyxfilename, pyxbuild_dir, is_package, build_inplace, language_level, so_path)[0m
[1;32m    212[0m     [38;5;28;01melse[39;00m:
[1;32m    213[0m         module_name [38;5;241m=[39m name
[0;32m--> 214[0m     so_path [38;5;241m=[39m [43mbuild_module[49m[43m([49m[43mmodule_name[49m[43m,[49m[43m [49m[43mpyxfilename[49m[43m,[49m[43m [49m[43mpyxbuild_dir[49m[43m,[49m
[1;32m    215[0m [43m                           [49m[43minplace[49m[38;5;241;43m=[39;49m[43mbuild_inplace[49m[43m,[49m[43m [49m[43mlanguage_level[49m[38;5;241;43m=[39;49m[43mlanguage_level[49m[43m)[49m
[1;32m    216[0m mod [38;5;241m=[39m imp[38;5;241m.[39mload_dynamic(name, so_path)
[1;32m    217[0m [38;5;28;01mif[39;00m is_package [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(mod, [38;5;124m'[39m[38;5;124m__path__[39m[38;5;124m'[39m):

File [0;32m~/.local/lib/python3.8/site-packages/pyximport/pyximport.py:176[0m, in [0;36mbuild_module[0;34m(name, pyxfilename, pyxbuild_dir, inplace, language_level)[0m
[1;32m    175[0m [38;5;28;01mdef[39;00m [38;5;21mbuild_module[39m(name, pyxfilename, pyxbuild_dir[38;5;241m=[39m[38;5;28;01mNone[39;00m, inplace[38;5;241m=[39m[38;5;28;01mFalse[39;00m, language_level[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m--> 176[0m     [38;5;28;01massert[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists(pyxfilename), [38;5;124m"[39m[38;5;124mPath does not exist: [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m [38;5;241m%[39m pyxfilename
[1;32m    177[0m     handle_dependencies(pyxfilename)
[1;32m    179[0m     extension_mod, setup_args [38;5;241m=[39m get_distutils_extension(name, pyxfilename, language_level)

[0;31mImportError[0m: Building module simpleNetwork_solver_run failed: ['AssertionError: Path does not exist: simpleNetwork_solver_run.pyx\n']
ImportError: Building module simpleNetwork_solver_run failed: ['AssertionError: Path does not exist: simpleNetwork_solver_run.pyx\n']

